name: Test github action

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  create_images:
    name: create container images
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set tag
        id: set-tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG="test-$SHORT_SHA"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/jtaeuber/tag-multiarch-images
          tags: |
            latest
            ${{ env.TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-push
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  test_action:
    name: test github action
    runs-on: ubuntu-latest
    needs: create_images
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Action
        uses: ./
        with:
          package_name: tag-multiarch-images
          gh_user: jtaeuber
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.create_images.outputs.tag }}
